<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "wms_ws_bill".
 *
 * @property int $id
 * @property string $ref 单号
 * @property string $action_time 业务发生日期
 * @property int $action_user_id 业务操作员
 * @property string $customer_id 客户id
 * @property string $create_time 出库单生成时间
 * @property string $inventory_money 本单据销售商品的库存价值
 * @property string $warehouse_id 仓库id
 * @property int $status 单据状态 0:待出库 1 ：已出库 2 : 已退货
 */
class WmsWsBill extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'wms_ws_bill';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'ref', 'action_time', 'action_user_id', 'customer_id', 'warehouse_id', 'status'], 'required'],
            [['id', 'action_user_id', 'status'], 'integer'],
            [['action_time', 'create_time'], 'safe'],
            [['inventory_money'], 'number'],
            [['ref', 'customer_id', 'warehouse_id'], 'string', 'max' => 255],
            [['id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ref' => 'Ref',
            'action_time' => 'Action Time',
            'action_user_id' => 'Action User ID',
            'customer_id' => 'Customer ID',
            'create_time' => 'Create Time',
            'inventory_money' => 'Inventory Money',
            'warehouse_id' => 'Warehouse ID',
            'status' => 'Status',
        ];
    }

    /*api返回字段
     * */
    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    /*出貨單（銷售出庫單）流水簿列表
     * */
    public function lis(){
        /*$sql = "SELECT * FROM wms_ws_bill ";
        $result= Yii::$app->db->createCommand($sql)->query();*/
//        $sql = "SELECT* FROM wms_ws_bill WHERE goods_id=:goods_id ";
//        return $sql;die;
//        var_dump($result);die;
//        $stock = Yii::$app->db->createCommand($sql)->bindValue(':goods_id', $goods_id)->bindValue(':warehouse_id', $warehouse_id)->queryOne();
//        $sql = "SELECT SUM(A.number) AS num FROM wms_so_bill_detail AS A LEFT JOIN wms_so_bill AS B ON A.oid = B.order_no WHERE A.sku_code=:sku AND B.status IN (5,6)";
//        $qty = Yii::$app->db->createCommand($sql)->bindValue(':sku', $sku)->queryOne();
//        return $stock['balance_count'] - $stock['lock_count'];
//        $result= self::find()->all();
//        $result= self::findOne(11);
//        $result= self::find()->where(['ref'=>1])->one();
//        $result= self::findBySql('select * from wms_ws_bill where id= 11')->count();
//        $result= self::findBySql('select * from wms_ws_bill ')->count();
//        $result= self::find()->andWhere(['ref'=>1,'status'=>1])->one();
//        $result= WmsWsBill::find()->count();
//        $result= WmsWsBill::find()->average('action_user_id');
//        $result= self::find()->min('action_user_id');

//        $result= self::find()->max('action_user_id');
//        var_dump($result);die;
//        $result= self::find()->scalar();
//        $result= self::find()->column();
        $result= self::find()->exists();
        return $result;
//        return $result;

    }

}
